version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    #bindmount
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    # docker-compose up --build 
    # docker-compose down